name: Generating Cypress report

on:
  schedule:
    - cron: "0 21 * * *"  # Runs every day at 12 AM Pakistan Time (UTC+5)
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  E2E-Testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Create .env file
        run: |
          echo CYPRESS_BASE_URL=${{ secrets.CYPRESS_UAT_URL }} >> .env
          echo CYPRESS_EMAIL=${{ secrets.CYPRESS_EMAIL }} >> .env
          echo CYPRESS_PASSWORD=${{ secrets.CYPRESS_PASSWORD }} >> .env
          echo CYPRESS_SNOWFLAKE_URL=${{ secrets.CYPRESS_SNOWFLAKE_UAT_URL }} >> .env

      - name: Run Cypress tests
        run: npm run cypress:run
        continue-on-error: true

      - name: Generate Report
        run: npm run posttest
        if: success() || failure()

      - name: Upload Test reports
        uses: actions/upload-artifact@v4.3.6
        if: success() || failure()
        with:
          name: reports
          path: cypress/reports/cucumber-html
